//public class ExceptionOrder {
//    public static void main(String[] args) {
//        try {
//            System.out.println(1 / 0);
//        } catch (RuntimeException e) {
//            System.out.println("Exception caught: " + e.getMessage());
//        } catch (ArithmeticException e) {
//            System.out.println("Arithmetic Exception caught: " + e.getMessage());
//        }
//    }
//}
